version: '3.8'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: nba_stats
      POSTGRES_USER: nba_stats_superuser
      POSTGRES_PASSWORD: nba_stats_superuser_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U example" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/nba_stats
      SPRING_DATASOURCE_USERNAME: nba_stats_superuser
      SPRING_DATASOURCE_PASSWORD: nba_stats_superuser_password
    networks:
      - frontend-backend
      - backend-db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - frontend-backend
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d

volumes:
  postgres_data:
networks:
  frontend-backend: { }
  backend-db: { }